import type { Question } from "./domain";

interface RecognitionItem {
  symbol: string;
  speechText: string;
  recordingUrl: string;
}

const syllableRecording = (name: string) => `/audio/audio-cmn/64k/syllabs/cmn-${name}.mp3`;
const wordRecording = (word: string) => `/audio/audio-cmn/64k/hsk/cmn-${word}.mp3`;

function recognitionQuestions(
  category: string,
  items: RecognitionItem[],
  group: string,
): Question[] {
  return items.map((item, index) => {
    const distractors = Array.from({ length: 3 }, (_, offset) =>
      items[(index + offset + 1) % items.length].symbol,
    );
    const options = [...distractors];
    options.splice(index % 4, 0, item.symbol);

    return {
      id: `py-recognition-${group}-${index + 1}`,
      subject: "pinyin",
      category,
      difficulty: category === "单韵母" ? 1 : 2,
      type: "choice",
      prompt: `听一听，选出 ${item.symbol}`,
      content: "第一阶段 · 认识拼音",
      answer: item.symbol,
      options,
      visual: item.symbol,
      assets: [],
      tags: [category, "发音", "认读"],
      metadata: { stage: 1, speechText: item.speechText, recordingUrl: item.recordingUrl },
    };
  });
}

const vowels: RecognitionItem[] = [
  ["a", "啊", "a1"], ["o", "喔", "o1"], ["e", "鹅", "e1"],
  ["i", "衣", "yi1"], ["u", "乌", "wu1"], ["ü", "迂", "yu1"],
].map(([symbol, speechText, recording]) => ({ symbol, speechText, recordingUrl: syllableRecording(recording) }));

const initials: RecognitionItem[] = [
  ["b", "玻", "bo1"], ["p", "坡", "po1"], ["m", "摸", "mo1"], ["f", "佛", "fo2"],
  ["d", "得", "de2"], ["t", "特", "te4"], ["n", "讷", "ne4"], ["l", "勒", "le4"],
  ["g", "哥", "ge1"], ["k", "科", "ke1"], ["h", "喝", "he1"], ["j", "鸡", "ji1"],
  ["q", "七", "qi1"], ["x", "西", "xi1"], ["zh", "知", "zhi1"], ["ch", "吃", "chi1"],
  ["sh", "诗", "shi1"], ["r", "日", "ri4"], ["z", "资", "zi1"], ["c", "雌", "ci2"],
  ["s", "思", "si1"], ["y", "衣", "yi1"], ["w", "乌", "wu1"],
].map(([symbol, speechText, recording]) => ({ symbol, speechText, recordingUrl: syllableRecording(recording) }));

const compoundFinals: RecognitionItem[] = [
  ["ai", "哀", "ai1"], ["ei", "诶", "ei1"], ["ui", "威", "wei1"],
  ["ao", "凹", "ao1"], ["ou", "欧", "ou1"], ["iu", "优", "you1"],
  ["ie", "耶", "ye1"], ["üe", "约", "yue1"], ["er", "儿", "er2"],
  ["an", "安", "an1"], ["en", "恩", "en1"], ["in", "因", "yin1"],
  ["un", "温", "wen1"], ["ün", "晕", "yun1"], ["ang", "昂", "ang1"],
  ["eng", "鞥", "eng1"], ["ing", "英", "ying1"], ["ong", "翁", "weng1"],
].map(([symbol, speechText, recording]) => ({ symbol, speechText, recordingUrl: syllableRecording(recording) }));

const wholeSyllables: RecognitionItem[] = [
  ["zhi", "知", "zhi1"], ["chi", "吃", "chi1"], ["shi", "诗", "shi1"],
  ["ri", "日", "ri4"], ["zi", "资", "zi1"], ["ci", "雌", "ci2"], ["si", "思", "si1"],
  ["yi", "衣", "yi1"], ["wu", "乌", "wu1"], ["yu", "迂", "yu1"], ["ye", "耶", "ye1"],
  ["yue", "约", "yue1"], ["yuan", "冤", "yuan1"], ["yin", "音", "yin1"],
  ["yun", "晕", "yun1"], ["ying", "英", "ying1"],
].map(([symbol, speechText, recording]) => ({ symbol, speechText, recordingUrl: syllableRecording(recording) }));

export const pinyinQuestions: Question[] = [
  ...recognitionQuestions("单韵母", vowels, "vowel"),
  ...recognitionQuestions("声母", initials, "initial"),
  ...recognitionQuestions("复韵母", compoundFinals, "final"),
  ...recognitionQuestions("整体认读", wholeSyllables, "whole"),
  {
    id: "py-vowel-a",
    subject: "pinyin",
    category: "单韵母",
    difficulty: 1,
    type: "choice",
    prompt: "听一听，找出刚才读到的单韵母",
    content: "第一阶段 · 认识拼音",
    answer: "a",
    options: ["a", "o", "e", "i"],
    visual: "a",
    assets: [],
    tags: ["单韵母", "发音"],
    metadata: { stage: 1, speechText: "啊", recordingUrl: syllableRecording("a1"), hint: "张大嘴巴 a a a" },
  },
  {
    id: "py-initial-b",
    subject: "pinyin",
    category: "声母",
    difficulty: 1,
    type: "choice",
    prompt: "哪一个是声母 b？",
    content: "第一阶段 · 认识声母",
    answer: "b",
    options: ["b", "p", "d", "q"],
    visual: "b",
    assets: [],
    tags: ["声母", "辨形"],
    metadata: { stage: 1, speechText: "玻", recordingUrl: syllableRecording("bo1"), hint: "右下半圆 b b b" },
  },
  {
    id: "py-compound-ai",
    subject: "pinyin",
    category: "复韵母",
    difficulty: 1,
    type: "choice",
    prompt: "哪一个是复韵母 ai？",
    content: "第一阶段 · 复韵母",
    answer: "ai",
    options: ["ai", "ei", "ui", "ao"],
    visual: "ai",
    assets: [],
    tags: ["复韵母", "发音组合"],
    metadata: { stage: 1, speechText: "哀", recordingUrl: syllableRecording("ai1"), hint: "从 a 的口型滑向 i" },
  },
  {
    id: "py-tone-ma",
    subject: "pinyin",
    category: "四声",
    difficulty: 1,
    type: "choice",
    prompt: "“妈”的正确拼音是？",
    content: "第二阶段 · 四声学习",
    answer: "mā",
    options: ["mā", "má", "mǎ", "mà"],
    visual: "妈",
    assets: [],
    tags: ["四声", "一声"],
    metadata: { stage: 2, tone: 1, speechText: "妈", recordingUrl: syllableRecording("ma1") },
  },
  {
    id: "py-whole-zhi",
    subject: "pinyin",
    category: "整体认读",
    difficulty: 2,
    type: "choice",
    prompt: "听读音，选择正确的整体认读音节",
    content: "第三阶段 · 整体认读音节",
    answer: "zhi",
    options: ["zhi", "chi", "shi", "ri"],
    visual: "知",
    assets: [],
    tags: ["整体认读", "听辨"],
    metadata: { stage: 3, speechText: "知", recordingUrl: syllableRecording("zhi1"), hint: "整体认读，不拆开拼" },
  },
  {
    id: "py-blend-ba",
    subject: "pinyin",
    category: "拼读",
    difficulty: 1,
    type: "match",
    prompt: "b 和 a 可以拼成什么？",
    content: "第四阶段 · 两拼音节",
    answer: "ba",
    options: ["ba", "bo", "pa", "ma"],
    visual: "b + a",
    assets: [],
    tags: ["拼读", "两拼音节"],
    metadata: { stage: 4, speechText: "八", recordingUrl: syllableRecording("ba1"), hint: "前音轻短，后音重" },
  },
  {
    id: "py-syllable-bang",
    subject: "pinyin",
    category: "音节",
    difficulty: 2,
    type: "match",
    prompt: "为“棒”找到正确拼音",
    content: "第五阶段 · 音节训练",
    answer: "bàng",
    options: ["bān", "bǎn", "bàng", "bāng"],
    visual: "👍",
    assets: [],
    tags: ["音节", "四声"],
    metadata: { stage: 5, speechText: "棒", recordingUrl: syllableRecording("bang4") },
  },
  {
    id: "py-word-apple",
    subject: "pinyin",
    category: "词语",
    difficulty: 2,
    type: "match",
    prompt: "给“苹果”找到正确拼音",
    content: "第六阶段 · 词语训练",
    answer: "píng guǒ",
    options: ["píng guǒ", "fēi jī", "lǎo shī", "mā ma"],
    visual: "🍎",
    assets: [],
    tags: ["词语", "拼读"],
    metadata: { stage: 6, speechText: "苹果", recordingUrl: wordRecording("苹果") },
  },
  {
    id: "py-sentence-cat",
    subject: "pinyin",
    category: "句子",
    difficulty: 3,
    type: "match",
    prompt: "哪一句拼音表示“小猫在睡觉”？",
    content: "第七阶段 · 句子训练",
    answer: "xiǎo māo zài shuì jiào",
    options: ["xiǎo māo zài shuì jiào", "wǒ ài mā ma", "jīn tiān tiān qì hěn hǎo"],
    visual: "🐱",
    assets: [],
    tags: ["句子", "阅读"],
    metadata: { stage: 7, speechText: "小猫在睡觉" },
  },
  {
    id: "py-listen-ma",
    subject: "pinyin",
    category: "听力",
    difficulty: 2,
    type: "choice",
    prompt: "点击朗读，选出听到的音节",
    content: "第八阶段 · 听力训练",
    answer: "ma",
    options: ["ma", "ba", "na", "la"],
    visual: "♪",
    assets: [],
    tags: ["听力", "音节"],
    metadata: { stage: 8, speechText: "妈", recordingUrl: syllableRecording("ma1") },
  },
  {
    id: "py-spell-ba",
    subject: "pinyin",
    category: "拼写",
    difficulty: 2,
    type: "spelling",
    prompt: "听一听，写出这个音节",
    content: "第九阶段 · 拼写训练",
    answer: "ba",
    options: [],
    visual: "b + a",
    assets: [],
    tags: ["拼写", "听音"],
    metadata: { stage: 9, speechText: "八", recordingUrl: syllableRecording("ba1"), hint: "由声母 b 和单韵母 a 组成" },
  },
  {
    id: "py-read-father",
    subject: "pinyin",
    category: "阅读",
    difficulty: 3,
    type: "spelling",
    prompt: "读一读，再写出对应的汉字",
    content: "第十阶段 · 阅读训练",
    answer: "爸爸爱我",
    options: [],
    visual: "bà ba ài wǒ",
    assets: [],
    tags: ["阅读", "句子"],
    metadata: { stage: 10, speechText: "爸爸爱我", hint: "爸爸爱我" },
  },
  {
    id: "py-review-airplane",
    subject: "pinyin",
    category: "综合测试",
    difficulty: 3,
    type: "choice",
    prompt: "听词语，选择正确的拼音",
    content: "第十一阶段 · 综合测试",
    answer: "fēi jī",
    options: ["fēi jī", "lǎo shī", "píng guǒ", "bà ba"],
    visual: "✈️",
    assets: [],
    tags: ["综合测试", "听辨", "拼读"],
    metadata: { stage: 11, speechText: "飞机", recordingUrl: wordRecording("飞机") },
  },
];
